# Generated by Django 5.1.2 on 2024-10-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comment_is_blocked_post_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="block_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="block_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
