# Generated by Django 5.1.2 on 2024-10-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment_block_reason_post_block_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="block_reason",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="block_reason",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
