# Generated by Django 5.1.2 on 2024-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_comment_block_reason_alter_post_block_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="auto_reply_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="reply_delay",
            field=models.IntegerField(default=0),
        ),
    ]
